const heroNameMapping = {
    rattletrap: 'Clockwerk',
    nevermore: 'Shadow Fiend',
    obsidian_destroyer: 'Outworld Destroyer',
    magnataur: 'Magnus',
    shredder: 'Timbersaw',
    furion: 'Nature\'s Prophet',
    wisp: 'Io',
    treant: 'Treant Protector',
    vengefulspirit: 'Vengeful Spirit',
    zuus: 'Zeus',
    necrolyte: 'Necrophos',
    queenofpain: 'Queen of Pain',
    skeletonking: 'Wraith King',
    faerie_dragon: 'Puck',
    templar_assassin: 'Templar Assassin',
    windrunner: 'Windranger',
    witch_doctor: 'Witch Doctor',
    tuskarr: 'Tusk',
    abyssal_underlord: 'Underlord',
    spirit_breaker: 'Spirit Breaker',
    shadow_shaman: 'Shadow Shaman',
    shadow_demon: 'Shadow Demon',
    shadow_priest: 'Dazzle',
    skeleton_king: 'Wraith King',
    storm_spirit: 'Storm Spirit',
    tidehunter: 'Tidehunter',
    tinker: 'Tinker',
    tiny: 'Tiny',
    treant_protector: 'Treant Protector',
    troll_warlord: 'Troll Warlord',
    tusk: 'Tusk',
    undying: 'Undying',
    ursa: 'Ursa',
    vengeful_spirit: 'Vengeful Spirit',
    venomancer: 'Venomancer',
    viper: 'Viper',
    visage: 'Visage',
    warlock: 'Warlock',
    weaver: 'Weaver',
    windranger: 'Windranger',
    winter_wyvern: 'Winter Wyvern',
    wraith_king: 'Wraith King',
    zeus: 'Zeus'
  };
  
  export default heroNameMapping;